4.1 Warming Up Exercise: Basic Vector and Matrix Operation with Numpy.
Problem - 1: Array Creation:
Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
import numpy as np
#Task 1:
empty_array = np.zeros((2, 2))
print("Empty array:")
print(empty_array)
#Task 2:
ones_array = np.ones((4,2))
print("all one array: ")
print(ones_array)
#Task 3:
fill_value_array = np.full((3,3), 7)
print("filled value array: ")
print(fill_value_array)
#Task 4:
given_array = np.zeros_like([[1,2,3], [4,5,6]])
print("given array: ")
print(given_array)
#Task 5:
ones_like_array = np.ones_like((given_array))
print("one like array: ")
print(ones_like_array)
#Task 6:
new_list = [1,2,3,4]
numpy_array = np.array(new_list)
print("numpy array: ")
print(numpy_array)

Empty array:
[[0. 0.]
 [0. 0.]]
all one array: 
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
filled value array: 
[[7 7 7]
 [7 7 7]
 [7 7 7]]
given array: 
[[0 0 0]
 [0 0 0]]
one like array: 
[[1 1 1]
 [1 1 1]]
numpy array: 
[1 2 3 4]


4.1.1 Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
import numpy as np
array_range = np.arange(10,50)
print(array_range)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
array_1d = np.arange(9)
matrix_3x3 = array_1d.reshape((3, 3))
print(matrix_3x3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
import numpy as np
random_array = np.random.random(30)
mean_value = random_array.mean()
print(mean_value)

0.46401795621639425


In [ ]:
random_array = np.random.rand(10, 10)
min_value = random_array.min()
max_value = random_array.max()
print(min_value, max_value)

0.006088759538443678 0.9950594380339514


In [ ]:
zeros_array = np.zeros(10)
zeros_array[4] = 1
print(zeros_array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print(reversed_arr)

[0 4 0 0 2 1]


In [ ]:
shape = (5,5)
array_2d = np.ones(shape, dtype=int)
array_2d[1:-1, 1:-1] = 0
print(array_2d)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [ ]:
checkerboard = np.zeros((8,8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Problem 3: Array Operation

In [ ]:
x = np.array([[1,2], [3,5]])
y = np.array([[5,6], [7,8]])
v = np.array([9,10])
w = np.array([11,12])
add_xy = x + y
add_vw = v + w

sub_xy = x - y
sub_vw = v - w

mult_xy = x * y
mult_vw = v * w

sq_x = x**2
sq_y = y**2

dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)

concat_xy_row = np.concatenate((x, y), axis=0)
concat_vw_col = np.concatenate((v[:, np.newaxis], w[:, np.newaxis]), axis=1)



Problem 4: Matrix Operation

In [ ]:
import numpy as np

A = np.array([[3,4], [7,8]])
A_inv = np.linalg.inv(A)
I = np.dot(A, A_inv)
print(I)

[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [ ]:
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

AB = np.dot(A, B)
BA = np.dot(B, A)

print(AB)
print(BA)

[[23 13]
 [51 29]]
[[36 44]
 [13 16]]


In [ ]:
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

AB = np.dot(A, B)
AB_T = AB.T

B_T = B.T
A_T = A.T
BT_AT = np.dot(B_T, A_T)

print(AB_T)
print(BT_AT)

[[23 51]
 [13 29]]
[[23 51]
 [13 29]]


In [ ]:

A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
b = np.array([-1, -3, 9])

A_inv = np.linalg.inv(A)
x = np.dot(A_inv, b)
print(x)

[ 2.  1. -2.]


In [ ]:

A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
b = np.array([-1, -3, 9])


x = np.linalg.solve(A, b)

print(x)

[ 2.  1. -2.]


experiment


In [ ]:
import numpy as np
import time

# Define sizes
list_size = 1_000_000
matrix_size = 1000

# Create lists and arrays
list1 = [i for i in range(list_size)]
list2 = [i for i in range(list_size)]

array1 = np.array(list1)
array2 = np.array(list2)

# 1. Element-wise Addition
# Python lists
start_time = time.time()
result_list_add = [list1[i] + list2[i] for i in range(list_size)]
list_add_time = time.time() - start_time

# NumPy arrays
start_time = time.time()
result_array_add = array1 + array2
array_add_time = time.time() - start_time

print(f"Element-wise Addition: Python Lists = {list_add_time:.6f}s, NumPy Arrays = {array_add_time:.6f}s")

# 2. Element-wise Multiplication
# Python lists
start_time = time.time()
result_list_mul = [list1[i] * list2[i] for i in range(list_size)]
list_mul_time = time.time() - start_time

# NumPy arrays
start_time = time.time()
result_array_mul = array1 * array2
array_mul_time = time.time() - start_time

print(f"Element-wise Multiplication: Python Lists = {list_mul_time:.6f}s, NumPy Arrays = {array_mul_time:.6f}s")

# 3. Dot Product
# Python lists
start_time = time.time()
result_list_dot = sum(list1[i] * list2[i] for i in range(list_size))
list_dot_time = time.time() - start_time

# NumPy arrays
start_time = time.time()
result_array_dot = np.dot(array1, array2)
array_dot_time = time.time() - start_time

print(f"Dot Product: Python Lists = {list_dot_time:.6f}s, NumPy Arrays = {array_dot_time:.6f}s")


matrix1 = [[i for i in range(matrix_size)] for _ in range(matrix_size)]
matrix2 = [[i for i in range(matrix_size)] for _ in range(matrix_size)]

np_matrix1 = np.array(matrix1)
np_matrix2 = np.array(matrix2)

# Python lists
start_time = time.time()
result_matrix = [[sum(a * b for a, b in zip(matrix1_row, matrix2_col)) for matrix2_col in zip(*matrix2)] for matrix1_row in matrix1]
matrix_mul_time = time.time() - start_time

# NumPy arrays
start_time = time.time()
result_np_matrix = np.dot(np_matrix1, np_matrix2)
np_matrix_mul_time = time.time() - start_time

print(f"Matrix Multiplication: Python Lists = {matrix_mul_time:.6f}s, NumPy Arrays = {np_matrix_mul_time:.6f}s")